plugins {
    id "com.android.application"
}

android {
    namespace = "com.whw.videowallpaper"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.whw.videowallpaper"
        minSdk = 29
        targetSdk = 37
        versionCode = 1
        versionName = "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    lint {
        abortOnError = true
        checkReleaseBuilds = true
        disable += "AndroidGradlePluginVersion"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
